// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID            string `json:"id"`
	ParentPost    string `json:"parentPost"`
	ParentComment string `json:"parentComment"`
	Commenter     string `json:"commenter"`
	Content       string `json:"content"`
	Postdate      string `json:"postdate"`
	Liker         string `json:"liker"`
}

type Education struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userID"`
	Institution string  `json:"institution"`
	Degree      string  `json:"degree"`
	Field       string  `json:"field"`
	Grade       float64 `json:"grade"`
	IsActive    bool    `json:"isActive"`
	StartYear   int     `json:"startYear"`
	EndYear     int     `json:"endYear"`
	Activities  string  `json:"activities"`
	Desc        string  `json:"desc"`
}

type Experience struct {
	ID        string `json:"id"`
	UserID    string `json:"userID"`
	Title     string `json:"title"`
	Type      string `json:"type"`
	Company   string `json:"company"`
	Country   string `json:"country"`
	IsActive  bool   `json:"isActive"`
	StartYear int    `json:"startYear"`
	EndYear   int    `json:"endYear"`
}

type Hashtag struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type InputActivate struct {
	ActivationID string `json:"activationID"`
}

type InputComment struct {
	ParentPost    string `json:"parentPost"`
	ParentComment string `json:"parentComment"`
	Commenter     string `json:"commenter"`
	Content       string `json:"content"`
	Postdate      string `json:"postdate"`
}

type InputConnectFollowBlock struct {
	ID  string `json:"id"`
	ID2 string `json:"id2"`
}

type InputEducation struct {
	UserID      string  `json:"userID"`
	Institution string  `json:"institution"`
	Degree      string  `json:"degree"`
	Field       string  `json:"field"`
	Grade       float64 `json:"grade"`
	IsActive    bool    `json:"isActive"`
	StartYear   int     `json:"startYear"`
	EndYear     int     `json:"endYear"`
	Activities  string  `json:"activities"`
	Desc        string  `json:"desc"`
}

type InputExperience struct {
	UserID    string `json:"userID"`
	Title     string `json:"title"`
	Type      string `json:"type"`
	Company   string `json:"company"`
	Country   string `json:"country"`
	IsActive  bool   `json:"isActive"`
	StartYear int    `json:"startYear"`
	EndYear   int    `json:"endYear"`
}

type InputLikeComment struct {
	ID    string `json:"id"`
	Liker string `json:"liker"`
}

type InputLikePost struct {
	ID    string `json:"id"`
	Liker string `json:"liker"`
}

type InputLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Google   string `json:"google"`
}

type InputNewJobPost struct {
	Poster      string `json:"poster"`
	Title       string `json:"title"`
	Company     string `json:"company"`
	Location    string `json:"location"`
	Employment  string `json:"employment"`
	Description string `json:"description"`
}

type InputNewPass struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type InputPost struct {
	Poster   string `json:"poster"`
	Content  string `json:"content"`
	Image    string `json:"image"`
	Video    string `json:"video"`
	Postdate string `json:"postdate"`
}

type InputRegister struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Google   string `json:"google"`
	Profile  string `json:"profile"`
}

type InputResetCode struct {
	ResetID string `json:"resetID"`
}

type InputResetPass struct {
	Email string `json:"email"`
}

type InputSetComment struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type InputSetEducation struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userID"`
	Institution string  `json:"institution"`
	Degree      string  `json:"degree"`
	Field       string  `json:"field"`
	Grade       float64 `json:"grade"`
	IsActive    bool    `json:"isActive"`
	StartYear   int     `json:"startYear"`
	EndYear     int     `json:"endYear"`
	Activities  string  `json:"activities"`
	Desc        string  `json:"desc"`
}

type InputSetExperience struct {
	ID        string `json:"id"`
	UserID    string `json:"userID"`
	Title     string `json:"title"`
	Type      string `json:"type"`
	Company   string `json:"company"`
	Country   string `json:"country"`
	IsActive  bool   `json:"isActive"`
	StartYear int    `json:"startYear"`
	EndYear   int    `json:"endYear"`
}

type InputSetPost struct {
	ID      string `json:"id"`
	Poster  string `json:"poster"`
	Content string `json:"content"`
	Image   string `json:"image"`
	Video   string `json:"video"`
}

type InputUpdateProfile struct {
	ID       string `json:"id"`
	Profile  string `json:"profile"`
	Name     string `json:"name"`
	Headline string `json:"headline"`
	Cover    string `json:"cover"`
}

type InputView struct {
	ID string `json:"id"`
}

type Job struct {
	ID          string `json:"id"`
	Poster      string `json:"poster"`
	Title       string `json:"title"`
	Company     string `json:"company"`
	Location    string `json:"location"`
	Employment  string `json:"employment"`
	Description string `json:"description"`
}

type Post struct {
	ID       string `json:"id"`
	Poster   string `json:"poster"`
	Content  string `json:"content"`
	Image    string `json:"image"`
	Video    string `json:"video"`
	Postdate string `json:"postdate"`
	Liker    string `json:"liker"`
}

type User struct {
	ID             string `json:"id"`
	Profile        string `json:"profile"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	Username       string `json:"username"`
	Password       string `json:"password"`
	Headline       string `json:"headline"`
	Cover          string `json:"cover"`
	Activated      bool   `json:"activated"`
	ActivationID   string `json:"activationID"`
	Followed       string `json:"followed"`
	Connected      string `json:"connected"`
	Requestconnect string `json:"requestconnect"`
	Blocked        string `json:"blocked"`
	Views          int    `json:"views"`
	ResetID        string `json:"resetID"`
	Google         string `json:"google"`
}
